export interface GitHubStatus {
  status: 'NOT_CONFIGURED' | 'CONNECTED' | 'SYNCED';
  repository?: string;
  branch: string;
  lastCommit?: string;
  setupInstructions?: string;
}

export class GitHubProvider {
  private isConfigured: boolean = false;
  private repoName?: string;

  constructor() {
    this.isConfigured = !!process.env.GITHUB_TOKEN;
  }

  public getStatus(projectName: string): GitHubStatus {
    if (!this.isConfigured) {
      return {
        status: 'NOT_CONFIGURED',
        branch: 'main',
        setupInstructions: 'Defina a variável de ambiente GITHUB_TOKEN para sincronizar repositórios privados ou públicos automaticamente.'
      };
    }

    return {
      status: 'SYNCED',
      repository: `https://github.com/org/${projectName.toLowerCase().replace(/\s+/g, '-')}`,
      branch: 'main',
      lastCommit: 'feat: autogenerated by BUD Agent Engine'
    };
  }

  public async syncRepository(projectName: string) {
    if (!this.isConfigured) {
      return {
        success: false,
        status: 'NOT_CONFIGURED',
        message: 'GitHub não configurado. Para conectar, configure seu Personal Access Token.'
      };
    }

    return {
      success: true,
      status: 'SYNCED',
      message: `Repositório ${projectName} sincronizado com sucesso na branch main.`
    };
  }
}

export const githubProvider = new GitHubProvider();
