import { useMemo, useState } from 'react';
import { ArrowRight, Check, Clipboard, ExternalLink, MapPin, Search, Sparkles } from 'lucide-react';
import { useAuth } from '../../auth/AuthContext';

interface Lead { id: string; name: string; address: string; lat: number; lon: number; mapUrl: string; category?: string; phone?: string; website?: string; }

const baseMessage = (lead: Lead) => `Olá, ${lead.name}! Tudo bem? Vi a presença da sua empresa no Google Maps e preparei uma ideia de site profissional para apresentar melhor seus serviços e facilitar novos contatos. Posso te mostrar uma prévia sem compromisso?`;

export default function BeginnerLeadCoach() {
  const { user, isAdmin } = useAuth();
  const [query, setQuery] = useState('clínicas');
  const [near, setNear] = useState('minha cidade');
  const [leads, setLeads] = useState<Lead[]>([]);
  const [selected, setSelected] = useState<Lead | null>(null);
  const [message, setMessage] = useState('');
  const [phone, setPhone] = useState('');
  const [step, setStep] = useState(1);
  const [loading, setLoading] = useState(false);
  const [copied, setCopied] = useState(false);
  const [error, setError] = useState('');
  const headers = { 'x-account-id': user?.uid || 'anonymous', 'x-plan-id': isAdmin ? 'admin_lifetime' : 'free' };

  const whatsappUrl = useMemo(() => `https://wa.me/${phone.replace(/\D/g, '')}?text=${encodeURIComponent(message || (selected ? baseMessage(selected) : ''))}`, [message, selected, phone]);

  async function searchLeads(event: React.FormEvent) {
    event.preventDefault(); setLoading(true); setError('');
    try { const response = await fetch(`/api/leads/search?q=${encodeURIComponent(query)}&near=${encodeURIComponent(near)}`, { headers }); const data = await response.json(); if (!response.ok) throw new Error(data.error); setLeads(data.leads || []); setStep(2); }
    catch (err: any) { setError(err.message || 'Não foi possível buscar leads.'); }
    finally { setLoading(false); }
  }

  function chooseLead(lead: Lead) { setSelected(lead); const nextMessage = baseMessage(lead); setMessage(nextMessage); setCopied(false); setStep(3); }
  async function copyMessage() { await navigator.clipboard?.writeText(message); setCopied(true); }
  function createSite() { if (!selected) return; const prompt = `Crie um site profissional para ${selected.name}, negócio do nicho ${query}, localizado em ${selected.address}. Gere uma prévia comercial para eu apresentar ao proprietário, com CTA de contato e proposta clara.`; window.location.href = `/?prompt=${encodeURIComponent(prompt)}`; }

  const steps = [['1', 'Escolha o nicho'], ['2', 'Encontre o lead'], ['3', 'Confira os dados'], ['4', 'Crie a prévia'], ['5', 'Entre em contato']];
  return <main className="min-h-screen bg-[#07090E] text-white p-4 sm:p-8"><div className="max-w-6xl mx-auto"><div className="flex flex-col sm:flex-row justify-between gap-4 items-start sm:items-center"><div><div className="inline-flex items-center gap-2 text-blue-300 text-xs font-bold uppercase tracking-widest"><Sparkles className="w-4 h-4" /> Primeiro cliente</div><h1 className="text-3xl sm:text-5xl font-black mt-2">Seu primeiro site vendido, passo a passo.</h1><p className="text-slate-400 mt-3 max-w-2xl">Você não precisa entender de programação. O SupremoBuild encontra um negócio, monta uma apresentação e prepara uma mensagem profissional.</p></div><a href="/" className="text-sm text-slate-300 hover:text-white">Voltar ao criador</a></div>
<div className="grid grid-cols-2 md:grid-cols-5 gap-2 mt-8">{steps.map(([number, label]) => <div key={number} className={`rounded-xl border p-3 text-xs ${Number(number) <= step ? 'border-blue-500/50 bg-blue-500/10 text-blue-200' : 'border-slate-800 text-slate-500'}`}><b>{number}.</b> {label}</div>)}</div>
{step === 1 && <section className="mt-6 grid lg:grid-cols-[1fr_.8fr] gap-5"><form onSubmit={searchLeads} className="rounded-3xl border border-slate-800 bg-slate-900 p-5 sm:p-8"><h2 className="text-xl font-black">Comece escolhendo um nicho</h2><p className="text-sm text-slate-400 mt-2">Exemplo: clínicas, academias, restaurantes, salões ou imobiliárias.</p><label className="block text-xs text-slate-400 mt-6">Nicho</label><input value={query} onChange={e => setQuery(e.target.value)} className="w-full mt-2 rounded-xl bg-slate-950 border border-slate-700 px-4 py-3" placeholder="ex.: clínicas" required /><label className="block text-xs text-slate-400 mt-4">Cidade ou região</label><input value={near} onChange={e => setNear(e.target.value)} className="w-full mt-2 rounded-xl bg-slate-950 border border-slate-700 px-4 py-3" placeholder="ex.: São Paulo" required /><button disabled={loading} className="mt-5 w-full rounded-xl bg-blue-600 hover:bg-blue-500 px-4 py-3 font-bold flex items-center justify-center gap-2"><Search className="w-4 h-4" />{loading ? 'Buscando no mapa...' : 'Buscar meus primeiros leads'}</button>{error && <p className="text-red-300 text-sm mt-3">{error}</p>}</form><div className="rounded-3xl border border-slate-800 bg-slate-900/60 p-5 sm:p-8"><h2 className="font-black">Como funciona</h2><ul className="mt-4 space-y-4 text-sm text-slate-300"><li><b className="text-blue-300">1.</b> Você escolhe um nicho com demanda.</li><li><b className="text-blue-300">2.</b> O mapa mostra negócios públicos próximos.</li><li><b className="text-blue-300">3.</b> Você escolhe um e confere os dados.</li><li><b className="text-blue-300">4.</b> O SupremoBuild monta uma prévia real.</li><li><b className="text-blue-300">5.</b> Você recebe uma copy profissional para contato.</li></ul></div></section>}
{step === 2 && <section className="mt-6"><div className="flex justify-between items-center"><div><h2 className="text-2xl font-black">Escolha um negócio para abordar</h2><p className="text-sm text-slate-400 mt-1">Confira o mapa antes de copiar qualquer informação.</p></div><button onClick={() => setStep(1)} className="text-sm text-blue-300">Alterar busca</button></div><div className="grid md:grid-cols-2 lg:grid-cols-3 gap-4 mt-5">{leads.map(lead => <article key={lead.id} className="rounded-2xl border border-slate-800 bg-slate-900 p-5 hover:border-blue-500/50"><MapPin className="w-5 h-5 text-blue-400" /><h3 className="font-black mt-3">{lead.name}</h3><p className="text-xs text-slate-400 mt-2 min-h-10">{lead.address}</p><div className="flex gap-2 mt-4"><a href={lead.mapUrl} target="_blank" rel="noreferrer" className="flex-1 text-center rounded-lg border border-slate-700 px-3 py-2 text-xs"><ExternalLink className="inline w-3 h-3 mr-1" />Mapa</a><button onClick={() => chooseLead(lead)} className="flex-1 rounded-lg bg-blue-600 px-3 py-2 text-xs font-bold">Escolher</button></div></article>)}</div>{!leads.length && <p className="text-slate-500 mt-8">Nenhum negócio encontrado. Tente uma região maior.</p>}</section>}
{step >= 3 && selected && <section className="mt-6 grid lg:grid-cols-[.8fr_1.2fr] gap-5"><div className="rounded-3xl border border-slate-800 bg-slate-900 p-5 sm:p-8"><div className="text-xs text-emerald-300 font-bold uppercase">Lead selecionado</div><h2 className="text-2xl font-black mt-2">{selected.name}</h2><p className="text-sm text-slate-400 mt-3">{selected.address}</p><a href={selected.mapUrl} target="_blank" rel="noreferrer" className="inline-block mt-4 text-blue-300 text-sm">Abrir no mapa →</a><div className="mt-8 space-y-3"><button onClick={createSite} className="w-full rounded-xl bg-blue-600 hover:bg-blue-500 px-4 py-3 font-bold">Criar prévia deste cliente</button><button onClick={() => setStep(4)} className="w-full rounded-xl border border-slate-700 px-4 py-3 text-sm">Próximo passo</button></div></div><div className="rounded-3xl border border-slate-800 bg-slate-900 p-5 sm:p-8"><h2 className="text-xl font-black">Copy profissional pronta</h2><p className="text-sm text-slate-400 mt-2">Confirme o telefone público do negócio antes de enviar.</p><input value={phone} onChange={e => setPhone(e.target.value)} placeholder="WhatsApp/telefone com DDD" className="w-full mt-4 rounded-xl bg-slate-950 border border-slate-700 px-4 py-3" /><textarea value={message} onChange={e => setMessage(e.target.value)} className="w-full min-h-40 mt-5 rounded-xl bg-slate-950 border border-slate-700 px-4 py-3 text-sm leading-relaxed" /><div className="flex flex-wrap gap-3 mt-4"><button onClick={copyMessage} className="rounded-xl border border-slate-700 px-4 py-3 text-sm font-bold"><Clipboard className="inline w-4 h-4 mr-2" />{copied ? 'Copiado!' : 'Copiar mensagem'}</button><a href={phone.replace(/\D/g, '').length >= 10 ? whatsappUrl : '#'} target="_blank" rel="noreferrer" onClick={event => { if (phone.replace(/\D/g, '').length < 10) event.preventDefault(); else setStep(5); }} className="rounded-xl bg-green-600 hover:bg-green-500 px-4 py-3 text-sm font-bold">Abrir WhatsApp</a></div><p className="text-[11px] text-slate-500 mt-4">Use apenas dados públicos e confirme se o negócio aceita contato comercial. O SupremoBuild não raspa o Google Maps.</p></div></section>}</div></main>;
}
